name: Tinybird - Recommendations Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0,12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install requirements
        run: pip install -r scripts/python/requirements.txt
      - name: Generate recommendations
        env:
          TB_TOKEN: ${{ secrets.TB_TOKEN }}
          TB_HOST: ${{ secrets.TB_HOST }}
        run: python scripts/python/generate_embeddings.py
